site:
  name: 'HKUST-MIRC'
  site: 'https://hkust-mirc.github.io'
  base: '/' # Change this if you need to deploy to Github Pages, for example
  # base: '/Media-Intelligence-Research-Center-Webpage/'
  trailingSlash: false # Generate permalinks with or without "/" at the end

  googleSiteVerificationId: 'false' # Or some value,

# Default SEO metadata
metadata:
  title:
    default: 'HKUST-MIRC'
    template: '%s â€” HKUST-MIRC'
  description: 'HKUST Media Intelligence Research Center'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'HKUST-MIRC'
    images:
      - url: ''
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@twitter_user'
    site: '@twitter_user'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true # If the blog will be enabled
    postsPerPage: 6 # Number of posts per page

    post:
      isEnabled: true
      permalink: '/news/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'news' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true # If a widget with related posts is to be displayed below each post
    relatedPostsCount: 4 # Number of related posts to display

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
